version: '3.7'
services:
  nginx:
    build:
      context: ./nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./app:/app:cached

  php:
    build:
      context: ./phpfpm
    volumes:
      - ./app:/app:cached

  mysql:
    #restart: always
    #build:
    #  context: ./mysql
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306

  composer:
    image: composer:latest
    volumes:
     - ./app:/app
    command: [tail, -f, /dev/null]
